### ISSUE TITLE
[JENKINS-34209] Pipeline plugin installs in upgrade wizard throws exceptions

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-23#5690]
<p>Reported on IRC:</p>

```
[2016-04-13 07:14:46]  <benh57>	 rc1 update failed updating Multibranch
[2016-04-13 07:14:47]  <benh57>	 Pipeline: Multibranch    
[2016-04-13 07:14:47]  <benh57>	 Failure -
[2016-04-13 07:14:47]  <benh57>	 java.lang.NoClassDefFoundError: jenkins/scm/api/SCMNavigatorDescriptor
[2016-04-13 07:14:47]  <benh57>	     at jenkins.branch.CustomOrganizationFolderDescriptor.doAddSpecificDesc
[2016-04-13 07:15:47]  <benh57>	 it seems to have actually installed fine though, looks normal after restart
[2016-04-13 11:08:40]  <@​danielbeck>	 benh57_ Still around? If so, could you please explain what exactly was updated, and where you see the error message?
[2016-04-13 20:54:23]  <benh57_>	 danielbeck: that error message was on the initial plugin upgrade screen that appears when updating to 2.0rc1.
[2016-04-13 20:55:05]  <@​danielbeck>	 benh57_ To clarify, are you upgrading or installing new?
[2016-04-13 20:55:35]  <benh57_>	 upgrading from 1.6something
[2016-04-13 20:55:47]  <benh57_>	 i clicked the 'click here to finish updating!' screen
[2016-04-13 20:56:07]  <benh57_>	 however, after jenkins restarted, the plugin appears to have updated fine
[2016-04-13 20:56:31]  <benh57_>	 i can check the log for the exact full details and email that to you
[2016-04-13 20:59:29]  <benh57_>	 there are various SCM-related exceptions in there actually
[2016-04-13 20:59:51]  <benh57_>	 1) Error injecting constructor, java.lang.NoClassDefFoundError: jenkins/scm/api/SCMSourceObserver
[2016-04-13 20:59:51]  <benh57_>	   at jenkins.branch.OrganizationFolder$DescriptorImpl.<init>(OrganizationFolder.java:266)
[2016-04-13 21:00:11]  <benh57_>	 Apr 13, 2016 5:13:52 AM hudson.ExtensionFinder$GuiceFinder$SezpozModule configure
[2016-04-13 21:00:11]  <benh57_>	 WARNING: Failed to load jenkins.branch.BranchProjectFactory$HeadByItemImpl
[2016-04-13 21:00:11]  <benh57_>	 java.lang.InstantiationException: java.lang.NoClassDefFoundError: jenkins/scm/api/SCMHead$HeadByItem

```

<p>My guess: The old dependency system (<a href="https://issues.jenkins.io/browse/JENKINS-21486" title="Refuse to load a plugin if dependencies are disabled or outdated" class="issue-link" data-issue-key="JENKINS-21486"><del>JENKINS-21486</del></a> <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/sad.png" height="16" width="16" align="absmiddle" alt="" border="0"/> ) does not take into account that dependencies may exist but be outdated when trying to dynamically load a plugin.</p>

<p>In the case of an outdated SCM API plugin (judging from these messages), this results in exceptions upon Pipeline plugin installation.</p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34209" target="_blank">Pipeline plugin installs in upgrade wizard throws exceptions</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>component(s)</b>: core
<li><b>label(s)</b>: 2.0, 2.0-rc
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2024-01-04T16:09:48+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 3
<li><b>imported</b>: 2025-11-23
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Reported on IRC:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>[2016-04-13 07:14:46]  &lt;benh57&gt;	 rc1 update failed updating Multibranch
[2016-04-13 07:14:47]  &lt;benh57&gt;	 Pipeline: Multibranch    
[2016-04-13 07:14:47]  &lt;benh57&gt;	 Failure -
[2016-04-13 07:14:47]  &lt;benh57&gt;	 java.lang.NoClassDefFoundError: jenkins/scm/api/SCMNavigatorDescriptor
[2016-04-13 07:14:47]  &lt;benh57&gt;	     at jenkins.branch.CustomOrganizationFolderDescriptor.doAddSpecificDesc
[2016-04-13 07:15:47]  &lt;benh57&gt;	 it seems to have actually installed fine though, looks normal after restart
[2016-04-13 11:08:40]  &lt;@danielbeck&gt;	 benh57_ Still around? If so, could you please explain what exactly was updated, and where you see the error message?
[2016-04-13 20:54:23]  &lt;benh57_&gt;	 danielbeck: that error message was on the initial plugin upgrade screen that appears when updating to 2.0rc1.
[2016-04-13 20:55:05]  &lt;@danielbeck&gt;	 benh57_ To clarify, are you upgrading or installing new?
[2016-04-13 20:55:35]  &lt;benh57_&gt;	 upgrading from 1.6something
[2016-04-13 20:55:47]  &lt;benh57_&gt;	 i clicked the 'click here to finish updating!' screen
[2016-04-13 20:56:07]  &lt;benh57_&gt;	 however, after jenkins restarted, the plugin appears to have updated fine
[2016-04-13 20:56:31]  &lt;benh57_&gt;	 i can check the log for the exact full details and email that to you
[2016-04-13 20:59:29]  &lt;benh57_&gt;	 there are various SCM-related exceptions in there actually
[2016-04-13 20:59:51]  &lt;benh57_&gt;	 1) Error injecting constructor, java.lang.NoClassDefFoundError: jenkins/scm/api/SCMSourceObserver
[2016-04-13 20:59:51]  &lt;benh57_&gt;	   at jenkins.branch.OrganizationFolder$DescriptorImpl.&lt;init&gt;(OrganizationFolder.java:266)
[2016-04-13 21:00:11]  &lt;benh57_&gt;	 Apr 13, 2016 5:13:52 AM hudson.ExtensionFinder$GuiceFinder$SezpozModule configure
[2016-04-13 21:00:11]  &lt;benh57_&gt;	 WARNING: Failed to load jenkins.branch.BranchProjectFactory$HeadByItemImpl
[2016-04-13 21:00:11]  &lt;benh57_&gt;	 java.lang.InstantiationException: java.lang.NoClassDefFoundError: jenkins/scm/api/SCMHead$HeadByItem
</pre>
</div></div>

<p>My guess: The old dependency system (<a href="https://issues.jenkins.io/browse/JENKINS-21486" title="Refuse to load a plugin if dependencies are disabled or outdated" class="issue-link" data-issue-key="JENKINS-21486"><del>JENKINS-21486</del></a> <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/sad.png" height="16" width="16" align="absmiddle" alt="" border="0"/> ) does not take into account that dependencies may exist but be outdated when trying to dynamically load a plugin.</p>

<p>In the case of an outdated SCM API plugin (judging from these messages), this results in exceptions upon Pipeline plugin installation.</p></pre>
</details>
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> danielbeck:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34209?focusedId=254344&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-254344">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>FYI <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=kohsuke" class="user-hover" rel="kohsuke">kohsuke</a>.</p>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler" class="user-hover" rel="rtyler">rtyler</a> Something to investigate tomorrow, perhaps? Not trivial to reproduce, likely requires specifically installing an older version of the SCM API plugin.</p>
</pre>
</details>

</ul>
</details>

<p>FYI <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=kohsuke" class="user-hover" rel="kohsuke">kohsuke</a>.</p>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler" class="user-hover" rel="rtyler">rtyler</a> Something to investigate tomorrow, perhaps? Not trivial to reproduce, likely requires specifically installing an older version of the SCM API plugin.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/rtyler.png" title="rtyler's avatar" /> rtyler:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34209?focusedId=254355&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-254355">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I'll try to nail down some reproduction steps</p>
</pre>
</details>

</ul>
</details>

<p>I'll try to nail down some reproduction steps</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> danielbeck:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34209?focusedId=254357&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-254357">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Mercurial Plugin still depends on SCM API 0.1. These extension points were added in 0.3. So it should be possible setting up a Jenkins 1.651.1 install with Mercurial Plugin, manually downgrade SCM API to 0.2, restart, everything works, upgrade to 2.0 RC, install Pipelines, expect it to explode.</p>

</pre>
</details>

</ul>
</details>

<p>Mercurial Plugin still depends on SCM API 0.1. These extension points were added in 0.3. So it should be possible setting up a Jenkins 1.651.1 install with Mercurial Plugin, manually downgrade SCM API to 0.2, restart, everything works, upgrade to 2.0 RC, install Pipelines, expect it to explode.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> danielbeck:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34209?focusedId=254445&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-254445">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Reproducible by installing the latest weekly, then installing 2.0 RC on top of it, then installing these plugins. Will show a similar error for Credentials Plugin.</p>

<p>As Jenkins is showing the update center install progress screen, and tells people to restart, I don't think this is particularly critical. It's certainly not <em>nice</em>, but we're working on this behavior in the context of <a href="https://issues.jenkins.io/browse/JENKINS-21486" title="Refuse to load a plugin if dependencies are disabled or outdated" class="issue-link" data-issue-key="JENKINS-21486"><del>JENKINS-21486</del></a>, <a href="https://issues.jenkins.io/browse/JENKINS-34073" title="Plugin dependency fix (JENKINS-21486) not visible enough" class="issue-link" data-issue-key="JENKINS-34073"><del>JENKINS-34073</del></a> (which barely got pulled out of 2.0 due to risk of perceived regressions).</p>
</pre>
</details>

</ul>
</details>

<p>Reproducible by installing the latest weekly, then installing 2.0 RC on top of it, then installing these plugins. Will show a similar error for Credentials Plugin.</p>

<p>As Jenkins is showing the update center install progress screen, and tells people to restart, I don't think this is particularly critical. It's certainly not <em>nice</em>, but we're working on this behavior in the context of <a href="https://issues.jenkins.io/browse/JENKINS-21486" title="Refuse to load a plugin if dependencies are disabled or outdated" class="issue-link" data-issue-key="JENKINS-21486"><del>JENKINS-21486</del></a>, <a href="https://issues.jenkins.io/browse/JENKINS-34073" title="Plugin dependency fix (JENKINS-21486) not visible enough" class="issue-link" data-issue-key="JENKINS-34073"><del>JENKINS-34073</del></a> (which barely got pulled out of 2.0 due to risk of perceived regressions).</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/jglick.png" title="jglick's avatar" /> jglick:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-34209?focusedId=444207&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-444207">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Does not sound like it would still be reproducible.</p>
</pre>
</details>

</ul>
</details>

<p>Does not sound like it would still be reproducible.</p>
