### ISSUE TITLE
[JENKINS-36249] Jenkins Stuck at "Please wait while Jenkins is getting ready to work..." Screen

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-23#5951]
<p>Our instance of Jenkins is caught at the "Please wait while Jenkins is getting ready to work..." screen. Not quite sure when this starting occurring. We run nightly builds and build ran over the weekend just fine. Any help would be most appreciated. Attached are the log files.</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jfree1985">jfree1985</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-36249" target="_blank">Jenkins Stuck at "Please wait while Jenkins is getting ready to work..." Screen</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>component(s)</b>: core
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 4
<li><b>imported</b>: 2025-11-23
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Our instance of Jenkins is caught at the "Please wait while Jenkins is getting ready to work..." screen. Not quite sure when this starting occurring. We run nightly builds and build ran over the weekend just fine. Any help would be most appreciated. Attached are the log files.</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Windows 8.1 VM</code></li></ul>
<details><summary><i>1 attachment</i></summary>

- [jenkins.err.log](https://issues.jenkins.io/secure/attachment/33141/jenkins.err.log)
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>jfree1985:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-36249?focusedId=262558&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-262558">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Forgot to mention the Jenkins version. I'm running version 2.10</p>
</pre>
</details>

</ul>
</details>

<p>Forgot to mention the Jenkins version. I'm running version 2.10</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> danielbeck:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-36249?focusedId=263273&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-263273">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Please do this and look for deadlocks: <a href="https://wiki.jenkins-ci.org/display/JENKINS/Obtaining+a+thread+dump" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.jenkins-ci.org/display/JENKINS/Obtaining+a+thread+dump</a> </p>
</pre>
</details>

</ul>
</details>

<p>Please do this and look for deadlocks: <a href="https://wiki.jenkins-ci.org/display/JENKINS/Obtaining+a+thread+dump" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.jenkins-ci.org/display/JENKINS/Obtaining+a+thread+dump</a> </p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/tsauter.svg" title="tsauter's avatar" /> tsauter:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-36249?focusedId=264980&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-264980">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I had the same issue after upgrading Jenkins from version 1.6xx to 2.7.1.</p>

<p>The err.log also showed me the same lines.</p>
<blockquote><p>Jun 27, 2016 12:34:56 PM hudson.PluginManager$1$3$2$1 reactOnCycle
SEVERE: found cycle in plugin dependencies: (root=Plugin:git, deactivating all involved) Plugin:git -&gt; Plugin:workflow-scm-step -&gt; Plugin:git</p>

<p>Jun 27, 2016 12:35:11 PM hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException
SEVERE: A thread (pool-6-thread-6/32) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.NoClassDefFoundError: org/jenkinsci/plugins/github_branch_source/GitHubSCMSource</p></blockquote>

<p>After i updated manually the <b>workflow-scm-step</b> plugin, Jenkins was going on.
I think it is related to his issue <a href="https://issues.jenkins.io/browse/JENKINS-35247" title="Move git/svn steps out of workflow-scm-steps" class="issue-link" data-issue-key="JENKINS-35247"><del>JENKINS-35247</del></a>.</p>
</pre>
</details>

</ul>
</details>

<p>I had the same issue after upgrading Jenkins from version 1.6xx to 2.7.1.</p>

<p>The err.log also showed me the same lines.</p>
<blockquote><p>Jun 27, 2016 12:34:56 PM hudson.PluginManager$1$3$2$1 reactOnCycle<br/>
SEVERE: found cycle in plugin dependencies: (root=Plugin:git, deactivating all involved) Plugin:git -> Plugin:workflow-scm-step -> Plugin:git</p>

<p>Jun 27, 2016 12:35:11 PM hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException<br/>
SEVERE: A thread (pool-6-thread-6/32) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.<br/>
java.lang.NoClassDefFoundError: org/jenkinsci/plugins/github_branch_source/GitHubSCMSource</p></blockquote>

<p>After i updated manually the <b>workflow-scm-step</b> plugin, Jenkins was going on.<br/>
I think it is related to his issue <a href="https://issues.jenkins.io/browse/JENKINS-35247" title="Move git/svn steps out of workflow-scm-steps" class="issue-link" data-issue-key="JENKINS-35247"><del>JENKINS-35247</del></a>.</p>
