### ISSUE TITLE
[JENKINS-10696] Problem with libpam4j after 1.420

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-23#4709]
<p>When I upgrade from 1.420 to a newer version (including 1.425, just now) and attempt to load Jenkins after restart, I get this stack trace in jenkins.log:</p>

<p><span class="error">&#91;Winstone 2011/08/12 13:41:49&#93;</span> - Untrapped Error in Servlet<br/>
java.lang.NoClassDefFoundError: Could not initialize class org.jvnet.libpam.impl.CLibrary<br/>
	at org.jvnet.libpam.UnixUser.exists(UnixUser.java:116)<br/>
	at hudson.security.PAMSecurityRealm.loadUserByUsername(PAMSecurityRealm.java:93)<br/>
	at org.acegisecurity.ui.rememberme.TokenBasedRememberMeServices.loadUserDetails(TokenBasedRememberMeServices.java:308)<br/>
	at org.acegisecurity.ui.rememberme.TokenBasedRememberMeServices.autoLogin(TokenBasedRememberMeServices.java:218)<br/>
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:104)<br/>
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)<br/>
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
	at org.acegisecurity.ui.basicauth.BasicProcessingFilter.doFilter(BasicProcessingFilter.java:173)<br/>
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)<br/>
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:66)<br/>
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)<br/>
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)<br/>
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)<br/>
	at winstone.FilterConfiguration.execute(FilterConfiguration.java:195)<br/>
	at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:368)<br/>
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)<br/>
	at winstone.FilterConfiguration.execute(FilterConfiguration.java:195)<br/>
	at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:368)<br/>
	at winstone.RequestDispatcher.forward(RequestDispatcher.java:333)<br/>
	at winstone.RequestHandlerThread.processRequest(RequestHandlerThread.java:244)<br/>
	at winstone.RequestHandlerThread.run(RequestHandlerThread.java:150)<br/>
	at java.lang.Thread.run(Thread.java:662)</p>

<p>Security settings:<br/>
  Security realm: Unix user/group database<br/>
  Access control service name: sshd<br/>
  Authorization: logged-in users can do anything</p>

<p>I did <b>not</b> explicitly log out from the 1.420 install before upgrading.</p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/craigcottingham.png" title="craigcottingham's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=craigcottingham">craigcottingham</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-10696" target="_blank">Problem with libpam4j after 1.420</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>component(s)</b>: core
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2022-11-23T19:39:58+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 3
<li><b>imported</b>: 2025-11-23
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>When I upgrade from 1.420 to a newer version (including 1.425, just now) and attempt to load Jenkins after restart, I get this stack trace in jenkins.log:</p>

<p><span class="error">&#91;Winstone 2011/08/12 13:41:49&#93;</span> - Untrapped Error in Servlet
java.lang.NoClassDefFoundError: Could not initialize class org.jvnet.libpam.impl.CLibrary
	at org.jvnet.libpam.UnixUser.exists(UnixUser.java:116)
	at hudson.security.PAMSecurityRealm.loadUserByUsername(PAMSecurityRealm.java:93)
	at org.acegisecurity.ui.rememberme.TokenBasedRememberMeServices.loadUserDetails(TokenBasedRememberMeServices.java:308)
	at org.acegisecurity.ui.rememberme.TokenBasedRememberMeServices.autoLogin(TokenBasedRememberMeServices.java:218)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:104)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.basicauth.BasicProcessingFilter.doFilter(BasicProcessingFilter.java:173)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:66)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
	at winstone.FilterConfiguration.execute(FilterConfiguration.java:195)
	at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:368)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at winstone.FilterConfiguration.execute(FilterConfiguration.java:195)
	at winstone.RequestDispatcher.doFilter(RequestDispatcher.java:368)
	at winstone.RequestDispatcher.forward(RequestDispatcher.java:333)
	at winstone.RequestHandlerThread.processRequest(RequestHandlerThread.java:244)
	at winstone.RequestHandlerThread.run(RequestHandlerThread.java:150)
	at java.lang.Thread.run(Thread.java:662)</p>

<p>Security settings:
  Security realm: Unix user/group database
  Access control service name: sshd
  Authorization: logged-in users can do anything</p>

<p>I did <b>not</b> explicitly log out from the 1.420 install before upgrading.</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Amazon Linux (2.6.35.11-83.9.amzn1.i686 #1 SMP Sat Feb 19 23:41:56 UTC 2011 i686 i686 i386 GNU/Linux), JDK 1.6.0_24 and 1.6.0_26</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/craigcottingham.png" title="craigcottingham's avatar" /> craigcottingham:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-10696?focusedId=156742&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-156742">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I upgraded to LTS 1.424.1 last night, and the problem seems to have gone away, for now.</p>
</pre>
</details>

</ul>
</details>

<p>I upgraded to LTS 1.424.1 last night, and the problem seems to have gone away, for now.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/evernat.png" title="evernat's avatar" /> evernat:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-10696?focusedId=171069&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-171069">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>if the issue has gone away, resolving as "can not reproduce"</p>
</pre>
</details>

</ul>
</details>

<p>if the issue has gone away, resolving as "can not reproduce"</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>dkasak:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-10696?focusedId=232065&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-232065">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I'm seeing this issue also. I'm new to Jenkins, and have triggered this issue by installing a plugin and bouncing the service. The version of Ubuntu being used is out of my control.</p>

<p>I've unpacked the jenkins.war file, and went to manually add libpam4j-1.4.jar ( which a java dev here told me would work ) to the WEB-INF/lib folder, but saw that this war file already includes libpam4j-1.8.jar.</p>

<p>I would greatly appreciate it if someone could tell me how to resolve this issue ...</p>
</pre>
</details>

</ul>
</details>

<p>I'm seeing this issue also. I'm new to Jenkins, and have triggered this issue by installing a plugin and bouncing the service. The version of Ubuntu being used is out of my control.</p>

<p>I've unpacked the jenkins.war file, and went to manually add libpam4j-1.4.jar ( which a java dev here told me would work ) to the WEB-INF/lib folder, but saw that this war file already includes libpam4j-1.8.jar.</p>

<p>I would greatly appreciate it if someone could tell me how to resolve this issue ...</p>
