### ISSUE TITLE
[JENKINS-61261] Ivy ClassNotFoundException when using Grab

### ISSUE THREAD

**Issue by jenkins-infra-bot** [timja-org/jenkins-gh-issues-poc-11-23#33]
<p>We are getting the below exception when we try to initialize and configure Jenkins plugins through post build Groovy Script under init.groovy.d. We understood this is the issue with classloader not able to find ivy in its path. However, this is working with 2.176.2 and started breaking from 2.176.3.</p>

<p> <br/>
 <br/>
@​Grab('org.yaml:snakeyaml:1.17')<br/>
import java.util.logging.Logger<br/>
import org.codehaus.groovy.control.CompilerConfiguration<br/>
import org.yaml.snakeyaml.Yaml<br/>
....<br/>
 <br/>
 <br/>
java.lang.ClassNotFoundException: org.apache.ivy.core.settings.IvySettings at java.net.URLClassLoader.findClass(URLClassLoader.java:382) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:565) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) Caused: java.lang.NoClassDefFoundError: org/apache/ivy/core/settings/IvySettings<br/>
 <br/>
 <br/>
 <br/>
We performed various work around to resolve this and none of them were successful<br/>
 <br/>
Job-DSL or Event Listener plugin cannot used since this is a config script which execute before Jenkins plugin installation/configuration. Similarly none of the pipeline utilities steps can be used at this point.<br/>
 <br/>
Cannot copy Ivy.jar to $Jenkins_Home/war/WEB_INF/lib due to the fact we run Jenkins as a docker container and war path will be only exposed after docker run which eventually invokes init.groovy.d script.<br/>
 <br/>
Tried adding the jar through classloader.<br/>
 <br/>
 </p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=gowthamsig">gowthamsig</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-61261" target="_blank">Ivy ClassNotFoundException when using Grab</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>component(s)</b>: core
<li><b>label(s)</b>: classpath, groovy, ivy, jenkins
<li><b>resolution</b>: Not A Defect
<li><b>resolved</b>: 2020-03-10T13:42:33+00:00
<li><b>votes</b>: 1
<li><b>watchers</b>: 3
<li><b>imported</b>: 2025-11-23
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>We are getting the below exception when we try to initialize and configure Jenkins plugins through post build Groovy Script under init.groovy.d. We understood this is the issue with classloader not able to find ivy in its path. However, this is working with 2.176.2 and started breaking from 2.176.3.</p>

<p> 
 
@Grab('org.yaml:snakeyaml:1.17')
import java.util.logging.Logger
import org.codehaus.groovy.control.CompilerConfiguration
import org.yaml.snakeyaml.Yaml
....
 
 
java.lang.ClassNotFoundException: org.apache.ivy.core.settings.IvySettings at java.net.URLClassLoader.findClass(URLClassLoader.java:382) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:565) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) Caused: java.lang.NoClassDefFoundError: org/apache/ivy/core/settings/IvySettings
 
 
 
We performed various work around to resolve this and none of them were successful
 
Job-DSL or Event Listener plugin cannot used since this is a config script which execute before Jenkins plugin installation/configuration. Similarly none of the pipeline utilities steps can be used at this point.
 
Cannot copy Ivy.jar to $Jenkins_Home/war/WEB_INF/lib due to the fact we run Jenkins as a docker container and war path will be only exposed after docker run which eventually invokes init.groovy.d script.
 
Tried adding the jar through classloader.
 
 </p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Jenkins LTS docker</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/danielbeck.png" title="danielbeck's avatar" /> danielbeck:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-61261?focusedId=386188&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-386188">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Unlikely to be a core change given <a href="https://github.com/jenkinsci/jenkins/compare/jenkins-2.176.2...jenkins-2.176.3" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/compare/jenkins-2.176.2...jenkins-2.176.3</a></p>

<p>My best guess is init.groovy scripts see all plugins' classes and their dependencies, and you updated a plugin at the same time that used to have Ivy on the classpath, and now don't.</p>

<p>See <a href="https://github.com/jenkinsci/jenkins/pull/2374" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/2374</a> for a PR that never got merged, and recent comments indicating plugins that include Ivy.</p>
</pre>
</details>

</ul>
</details>

<p>Unlikely to be a core change given <a href="https://github.com/jenkinsci/jenkins/compare/jenkins-2.176.2...jenkins-2.176.3" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/compare/jenkins-2.176.2...jenkins-2.176.3</a></p>

<p>My best guess is init.groovy scripts see all plugins' classes and their dependencies, and you updated a plugin at the same time that used to have Ivy on the classpath, and now don't.</p>

<p>See <a href="https://github.com/jenkinsci/jenkins/pull/2374" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/2374</a> for a PR that never got merged, and recent comments indicating plugins that include Ivy.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>gowthamsig:</i></summary>

<ul>
<li><i>Original <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-61261?focusedId=386984&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-386984">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Found the issue is related to downloaded plugins not present at the plugins path.</p>
</pre>
</details>

</ul>
</details>

<p>Found the issue is related to downloaded plugins not present at the plugins path.</p>
